### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by Seelvia95**
We translated the strings.xml file and the plurals.xml file, then we uploaded it in the Fork. 
Let us know if it's ok or if it needs something more.

### CODE REVIEW

**Comment by Domi04151309** [comment]
Thanks for translating. Everything should work now and the translation will be available with the next release.

**Comment by Seelvia95** [comment]
Thank you!! Hope everything will work!

**Comment by Domi04151309** [comment]
Because of the new demo mode I've added two new strings. It would be amazing if you translated them as well.

```xml
<string name="setup_demo">Demo</string>
<string name="setup_demo_summary">You can use the demo mode to take a look at the application without any functionality. Enable root access for the app to work.</string>
```

**Comment by Domi04151309** [comment]
Also, in what way do you want to be credited in the release notes?

**Comment by Seelvia95** [comment]
Sure!
silly question: do you want us to create a new file with the two translated strings like we did for the other files? or can we just write the translation to you? (I guess the first option, but I was just wondering).
For the credit, since it's the first time for us, we don't really know which are the ways we can be credited in the release notes. Would name and surname be ok?

**Comment by Domi04151309** [comment]
Just sending the translation to me is ok too. Name is fine.

**Comment by Seelvia95** [comment]
Okay then!

here is the translation: 
<string name="setup_demo">Demo</string>
<string name="setup_demo_summary">Puoi usare la modalità demo per dare un\'occhiata all\'applicazione ma senza alcuna funzionalità. Abilita l\'accesso root per usare l\'app.</string>

For the names, just enter Silvia & Bianca, and if you want you can also add the link to my GitHub page.
Let me know if everything works properly!

**Pull request merged**
